'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

# Determine if number is even
# Runtime O(1)
def is_even(number):
	return number % 2



max_value = 4000000		# 4 million
sum = 0				# store sum of even-valued Fibonacci numbers

for i in range(